//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: DasProto.proto
namespace platform.dao.param
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"AvailableType")]
    public partial class AvailableType : global::ProtoBuf.IExtensible
    {
        public AvailableType() { }

        private int _current;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"current", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int current
        {
            get { return _current; }
            set { _current = value; }
        }
        private bool _bool_arg = default(bool);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"bool_arg", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(default(bool))]
        public bool bool_arg
        {
            get { return _bool_arg; }
            set { _bool_arg = value; }
        }
        private int _int32_arg = default(int);
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"int32_arg", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int int32_arg
        {
            get { return _int32_arg; }
            set { _int32_arg = value; }
        }
        private long _int64_arg = default(long);
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"int64_arg", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(long))]
        public long int64_arg
        {
            get { return _int64_arg; }
            set { _int64_arg = value; }
        }
        private double _double_arg = default(double);
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"double_arg", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(double))]
        public double double_arg
        {
            get { return _double_arg; }
            set { _double_arg = value; }
        }
        private string _string_arg = "";
        [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"string_arg", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string string_arg
        {
            get { return _string_arg; }
            set { _string_arg = value; }
        }
        private byte[] _bytes_arg = null;
        [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name = @"bytes_arg", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public byte[] bytes_arg
        {
            get { return _bytes_arg; }
            set { _bytes_arg = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"SqlParameters")]
    public partial class SqlParameters : global::ProtoBuf.IExtensible
    {
        public SqlParameters() { }

        private int _dbType = default(int);
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"dbType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int dbType
        {
            get { return _dbType; }
            set { _dbType = value; }
        }
        private int _direction = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"direction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int direction
        {
            get { return _direction; }
            set { _direction = value; }
        }
        private bool _isNull = default(bool);
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"isNull", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(default(bool))]
        public bool isNull
        {
            get { return _isNull; }
            set { _isNull = value; }
        }
        private string _name = "";
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name
        {
            get { return _name; }
            set { _name = value; }
        }
        private int _index = default(int);
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int index
        {
            get { return _index; }
            set { _index = value; }
        }
        private bool _sensitive = default(bool);
        [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"sensitive", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(default(bool))]
        public bool sensitive
        {
            get { return _sensitive; }
            set { _sensitive = value; }
        }
        private platform.dao.param.AvailableType _value = null;
        [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name = @"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public platform.dao.param.AvailableType value
        {
            get { return _value; }
            set { _value = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"RequestMessage")]
    public partial class RequestMessage : global::ProtoBuf.IExtensible
    {
        public RequestMessage() { }

        private platform.dao.param.StatementType _stateType = platform.dao.param.StatementType.SQL;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"stateType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(platform.dao.param.StatementType.SQL)]
        public platform.dao.param.StatementType stateType
        {
            get { return _stateType; }
            set { _stateType = value; }
        }
        private bool _master = default(bool);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"master", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(default(bool))]
        public bool master
        {
            get { return _master; }
            set { _master = value; }
        }
        private platform.dao.param.CRUD _crud = platform.dao.param.CRUD.GET;
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"crud", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(platform.dao.param.CRUD.GET)]
        public platform.dao.param.CRUD crud
        {
            get { return _crud; }
            set { _crud = value; }
        }
        private string _name = "";
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name
        {
            get { return _name; }
            set { _name = value; }
        }
        private readonly global::System.Collections.Generic.List<platform.dao.param.SqlParameters> _parameters = new global::System.Collections.Generic.List<platform.dao.param.SqlParameters>();
        [global::ProtoBuf.ProtoMember(5, Name = @"parameters", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<platform.dao.param.SqlParameters> parameters
        {
            get { return _parameters; }
        }

        private int _flags = default(int);
        [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int flags
        {
            get { return _flags; }
            set { _flags = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Request")]
    public partial class Request : global::ProtoBuf.IExtensible
    {
        public Request() { }

        private string _id;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string id
        {
            get { return _id; }
            set { _id = value; }
        }
        private string _db = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"db", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string db
        {
            get { return _db; }
            set { _db = value; }
        }
        private string _cred = "";
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"cred", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string cred
        {
            get { return _cred; }
            set { _cred = value; }
        }
        private platform.dao.param.RequestMessage _msg = null;
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public platform.dao.param.RequestMessage msg
        {
            get { return _msg; }
            set { _msg = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ResponseHeader")]
    public partial class ResponseHeader : global::ProtoBuf.IExtensible
    {
        public ResponseHeader() { }

        private string _name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string name
        {
            get { return _name; }
            set { _name = value; }
        }
        private int _type;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int type
        {
            get { return _type; }
            set { _type = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Response")]
    public partial class Response : global::ProtoBuf.IExtensible
    {
        public Response() { }

        private string _id;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string id
        {
            get { return _id; }
            set { _id = value; }
        }
        private platform.dao.param.CRUD _resultType = platform.dao.param.CRUD.GET;
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"resultType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(platform.dao.param.CRUD.GET)]
        public platform.dao.param.CRUD resultType
        {
            get { return _resultType; }
            set { _resultType = value; }
        }
        private readonly global::System.Collections.Generic.List<platform.dao.param.ResponseHeader> _header = new global::System.Collections.Generic.List<platform.dao.param.ResponseHeader>();
        [global::ProtoBuf.ProtoMember(3, Name = @"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<platform.dao.param.ResponseHeader> header
        {
            get { return _header; }
        }

        private int _affectRows = default(int);
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"affectRows", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int affectRows
        {
            get { return _affectRows; }
            set { _affectRows = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Row")]
    public partial class Row : global::ProtoBuf.IExtensible
    {
        public Row() { }

        private readonly global::System.Collections.Generic.List<platform.dao.param.AvailableType> _columns = new global::System.Collections.Generic.List<platform.dao.param.AvailableType>();
        [global::ProtoBuf.ProtoMember(1, Name = @"columns", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<platform.dao.param.AvailableType> columns
        {
            get { return _columns; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"InnerResultSet")]
    public partial class InnerResultSet : global::ProtoBuf.IExtensible
    {
        public InnerResultSet() { }

        private bool _last;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"last", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public bool last
        {
            get { return _last; }
            set { _last = value; }
        }
        private readonly global::System.Collections.Generic.List<platform.dao.param.Row> _rows = new global::System.Collections.Generic.List<platform.dao.param.Row>();
        [global::ProtoBuf.ProtoMember(2, Name = @"rows", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<platform.dao.param.Row> rows
        {
            get { return _rows; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::ProtoBuf.ProtoContract(Name = @"CRUD")]
    public enum CRUD
    {

        [global::ProtoBuf.ProtoEnum(Name = @"GET", Value = 0)]
        GET = 0,

        [global::ProtoBuf.ProtoEnum(Name = @"CUD", Value = 1)]
        CUD = 1
    }

    [global::ProtoBuf.ProtoContract(Name = @"StatementType")]
    public enum StatementType
    {

        [global::ProtoBuf.ProtoEnum(Name = @"SQL", Value = 0)]
        SQL = 0,

        [global::ProtoBuf.ProtoEnum(Name = @"SP", Value = 1)]
        SP = 1
    }

}