//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arch.Data.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arch.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The app is marked as down, cantact the app internals administrator(the one can modify configuration through app internals) for more information!.
        /// </summary>
        internal static string AppMarkDownException
        {
            get
            {
                return ResourceManager.GetString("AppMarkDownException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DAL.config not found, check web.config or ConfigGen first!.
        /// </summary>
        public static String DalConfigNotFoundException
        {
            get
            {
                return ResourceManager.GetString("DalConfigNotFoundException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dal Phase error, can not navigate to next phase, current phase is {0}.
        /// </summary>
        internal static string DalTracingNextPhaseException
        {
            get
            {
                return ResourceManager.GetString("DalTracingNextPhaseException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1.4.1.0.
        /// </summary>
        internal static string DALVersion
        {
            get
            {
                return ResourceManager.GetString("DALVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Database set &apos;{0}&apos; doesn&apos;t exist!.
        /// </summary>
        internal static string DatabaseSetDoesNotExistException
        {
            get
            {
                return ResourceManager.GetString("DatabaseSetDoesNotExistException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This all in one key {0} is marked as down, can not execute database operation, cantact the app internals administrator(the one can modify configuration through app internals) for more information!.
        /// </summary>
        internal static string DBMarkDownException
        {
            get
            {
                return ResourceManager.GetString("DBMarkDownException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Database provider &apos;{0}&apos; type is invalid, maybe you missed a reference!.
        /// </summary>
        internal static string InvalidDatabaseProviderException
        {
            get
            {
                return ResourceManager.GetString("InvalidDatabaseProviderException", resourceCulture);
            }
        }
    }
}
