// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: das/ResultSet.proto

package com.ctrip.sysdev.das.domain;

public final class DasResultSet {
  private DasResultSet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DasResultSetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bool last = 1;
    /**
     * <code>required bool last = 1;</code>
     */
    boolean hasLast();
    /**
     * <code>required bool last = 1;</code>
     */
    boolean getLast();

    // repeated .sysdev.das.DasResultSet.Row rows = 2;
    /**
     * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
     */
    java.util.List<com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row> 
        getRowsList();
    /**
     * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
     */
    com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row getRows(int index);
    /**
     * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
     */
    int getRowsCount();
    /**
     * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
     */
    java.util.List<? extends com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.RowOrBuilder> 
        getRowsOrBuilderList();
    /**
     * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
     */
    com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.RowOrBuilder getRowsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code sysdev.das.DasResultSet}
   */
  public static final class InnerResultSet extends
      com.google.protobuf.GeneratedMessage
      implements DasResultSetOrBuilder {
    // Use DasResultSet.newBuilder() to construct.
    private InnerResultSet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InnerResultSet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InnerResultSet defaultInstance;
    public static InnerResultSet getDefaultInstance() {
      return defaultInstance;
    }

    public InnerResultSet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InnerResultSet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              last_ = input.readBool();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                rows_ = new java.util.ArrayList<com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row>();
                mutable_bitField0_ |= 0x00000002;
              }
              rows_.add(input.readMessage(com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          rows_ = java.util.Collections.unmodifiableList(rows_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ctrip.sysdev.das.domain.DasResultSet.internal_static_sysdev_das_DasResultSet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ctrip.sysdev.das.domain.DasResultSet.internal_static_sysdev_das_DasResultSet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.class, com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Builder.class);
    }

    public static com.google.protobuf.Parser<InnerResultSet> PARSER =
        new com.google.protobuf.AbstractParser<InnerResultSet>() {
      public InnerResultSet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InnerResultSet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InnerResultSet> getParserForType() {
      return PARSER;
    }

    public interface RowOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // repeated bytes columns = 1;
      /**
       * <code>repeated bytes columns = 1;</code>
       */
      java.util.List<com.google.protobuf.ByteString> getColumnsList();
      /**
       * <code>repeated bytes columns = 1;</code>
       */
      int getColumnsCount();
      /**
       * <code>repeated bytes columns = 1;</code>
       */
      com.google.protobuf.ByteString getColumns(int index);
    }
    /**
     * Protobuf type {@code sysdev.das.DasResultSet.Row}
     */
    public static final class Row extends
        com.google.protobuf.GeneratedMessage
        implements RowOrBuilder {
      // Use Row.newBuilder() to construct.
      private Row(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Row(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Row defaultInstance;
      public static Row getDefaultInstance() {
        return defaultInstance;
      }

      public Row getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Row(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                  columns_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                  mutable_bitField0_ |= 0x00000001;
                }
                columns_.add(input.readBytes());
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
            columns_ = java.util.Collections.unmodifiableList(columns_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ctrip.sysdev.das.domain.DasResultSet.internal_static_sysdev_das_DasResultSet_Row_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ctrip.sysdev.das.domain.DasResultSet.internal_static_sysdev_das_DasResultSet_Row_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row.class, com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row.Builder.class);
      }

      public static com.google.protobuf.Parser<Row> PARSER =
          new com.google.protobuf.AbstractParser<Row>() {
        public Row parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Row(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Row> getParserForType() {
        return PARSER;
      }

      // repeated bytes columns = 1;
      public static final int COLUMNS_FIELD_NUMBER = 1;
      private java.util.List<com.google.protobuf.ByteString> columns_;
      /**
       * <code>repeated bytes columns = 1;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getColumnsList() {
        return columns_;
      }
      /**
       * <code>repeated bytes columns = 1;</code>
       */
      public int getColumnsCount() {
        return columns_.size();
      }
      /**
       * <code>repeated bytes columns = 1;</code>
       */
      public com.google.protobuf.ByteString getColumns(int index) {
        return columns_.get(index);
      }

      private void initFields() {
        columns_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        for (int i = 0; i < columns_.size(); i++) {
          output.writeBytes(1, columns_.get(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        {
          int dataSize = 0;
          for (int i = 0; i < columns_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(columns_.get(i));
          }
          size += dataSize;
          size += 1 * getColumnsList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code sysdev.das.DasResultSet.Row}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.RowOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.ctrip.sysdev.das.domain.DasResultSet.internal_static_sysdev_das_DasResultSet_Row_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.ctrip.sysdev.das.domain.DasResultSet.internal_static_sysdev_das_DasResultSet_Row_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row.class, com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row.Builder.class);
        }

        // Construct using com.ctrip.sysdev.das.domain.ResultSet.DasResultSet.Row.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          columns_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.ctrip.sysdev.das.domain.DasResultSet.internal_static_sysdev_das_DasResultSet_Row_descriptor;
        }

        public com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row getDefaultInstanceForType() {
          return com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row.getDefaultInstance();
        }

        public com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row build() {
          com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row buildPartial() {
          com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row result = new com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row(this);
          int from_bitField0_ = bitField0_;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            columns_ = java.util.Collections.unmodifiableList(columns_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.columns_ = columns_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row) {
            return mergeFrom((com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row other) {
          if (other == com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row.getDefaultInstance()) return this;
          if (!other.columns_.isEmpty()) {
            if (columns_.isEmpty()) {
              columns_ = other.columns_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureColumnsIsMutable();
              columns_.addAll(other.columns_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // repeated bytes columns = 1;
        private java.util.List<com.google.protobuf.ByteString> columns_ = java.util.Collections.emptyList();
        private void ensureColumnsIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            columns_ = new java.util.ArrayList<com.google.protobuf.ByteString>(columns_);
            bitField0_ |= 0x00000001;
           }
        }
        /**
         * <code>repeated bytes columns = 1;</code>
         */
        public java.util.List<com.google.protobuf.ByteString>
            getColumnsList() {
          return java.util.Collections.unmodifiableList(columns_);
        }
        /**
         * <code>repeated bytes columns = 1;</code>
         */
        public int getColumnsCount() {
          return columns_.size();
        }
        /**
         * <code>repeated bytes columns = 1;</code>
         */
        public com.google.protobuf.ByteString getColumns(int index) {
          return columns_.get(index);
        }
        /**
         * <code>repeated bytes columns = 1;</code>
         */
        public Builder setColumns(
            int index, com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureColumnsIsMutable();
          columns_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated bytes columns = 1;</code>
         */
        public Builder addColumns(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureColumnsIsMutable();
          columns_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated bytes columns = 1;</code>
         */
        public Builder addAllColumns(
            java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
          ensureColumnsIsMutable();
          super.addAll(values, columns_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated bytes columns = 1;</code>
         */
        public Builder clearColumns() {
          columns_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:sysdev.das.DasResultSet.Row)
      }

      static {
        defaultInstance = new Row(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:sysdev.das.DasResultSet.Row)
    }

    private int bitField0_;
    // required bool last = 1;
    public static final int LAST_FIELD_NUMBER = 1;
    private boolean last_;
    /**
     * <code>required bool last = 1;</code>
     */
    public boolean hasLast() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool last = 1;</code>
     */
    public boolean getLast() {
      return last_;
    }

    // repeated .sysdev.das.DasResultSet.Row rows = 2;
    public static final int ROWS_FIELD_NUMBER = 2;
    private java.util.List<com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row> rows_;
    /**
     * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
     */
    public java.util.List<com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row> getRowsList() {
      return rows_;
    }
    /**
     * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
     */
    public java.util.List<? extends com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.RowOrBuilder> 
        getRowsOrBuilderList() {
      return rows_;
    }
    /**
     * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
     */
    public int getRowsCount() {
      return rows_.size();
    }
    /**
     * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
     */
    public com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row getRows(int index) {
      return rows_.get(index);
    }
    /**
     * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
     */
    public com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.RowOrBuilder getRowsOrBuilder(
        int index) {
      return rows_.get(index);
    }

    private void initFields() {
      last_ = false;
      rows_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasLast()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, last_);
      }
      for (int i = 0; i < rows_.size(); i++) {
        output.writeMessage(2, rows_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, last_);
      }
      for (int i = 0; i < rows_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, rows_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sysdev.das.DasResultSet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ctrip.sysdev.das.domain.DasResultSet.DasResultSetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ctrip.sysdev.das.domain.DasResultSet.internal_static_sysdev_das_DasResultSet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ctrip.sysdev.das.domain.DasResultSet.internal_static_sysdev_das_DasResultSet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.class, com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Builder.class);
      }

      // Construct using com.ctrip.sysdev.das.domain.ResultSet.DasResultSet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRowsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        last_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (rowsBuilder_ == null) {
          rows_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          rowsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ctrip.sysdev.das.domain.DasResultSet.internal_static_sysdev_das_DasResultSet_descriptor;
      }

      public com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet getDefaultInstanceForType() {
        return com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.getDefaultInstance();
      }

      public com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet build() {
        com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet buildPartial() {
        com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet result = new com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.last_ = last_;
        if (rowsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            rows_ = java.util.Collections.unmodifiableList(rows_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.rows_ = rows_;
        } else {
          result.rows_ = rowsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet) {
          return mergeFrom((com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet other) {
        if (other == com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.getDefaultInstance()) return this;
        if (other.hasLast()) {
          setLast(other.getLast());
        }
        if (rowsBuilder_ == null) {
          if (!other.rows_.isEmpty()) {
            if (rows_.isEmpty()) {
              rows_ = other.rows_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRowsIsMutable();
              rows_.addAll(other.rows_);
            }
            onChanged();
          }
        } else {
          if (!other.rows_.isEmpty()) {
            if (rowsBuilder_.isEmpty()) {
              rowsBuilder_.dispose();
              rowsBuilder_ = null;
              rows_ = other.rows_;
              bitField0_ = (bitField0_ & ~0x00000002);
              rowsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRowsFieldBuilder() : null;
            } else {
              rowsBuilder_.addAllMessages(other.rows_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLast()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bool last = 1;
      private boolean last_ ;
      /**
       * <code>required bool last = 1;</code>
       */
      public boolean hasLast() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool last = 1;</code>
       */
      public boolean getLast() {
        return last_;
      }
      /**
       * <code>required bool last = 1;</code>
       */
      public Builder setLast(boolean value) {
        bitField0_ |= 0x00000001;
        last_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool last = 1;</code>
       */
      public Builder clearLast() {
        bitField0_ = (bitField0_ & ~0x00000001);
        last_ = false;
        onChanged();
        return this;
      }

      // repeated .sysdev.das.DasResultSet.Row rows = 2;
      private java.util.List<com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row> rows_ =
        java.util.Collections.emptyList();
      private void ensureRowsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          rows_ = new java.util.ArrayList<com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row>(rows_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row, com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row.Builder, com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.RowOrBuilder> rowsBuilder_;

      /**
       * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
       */
      public java.util.List<com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row> getRowsList() {
        if (rowsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rows_);
        } else {
          return rowsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
       */
      public int getRowsCount() {
        if (rowsBuilder_ == null) {
          return rows_.size();
        } else {
          return rowsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
       */
      public com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row getRows(int index) {
        if (rowsBuilder_ == null) {
          return rows_.get(index);
        } else {
          return rowsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
       */
      public Builder setRows(
          int index, com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.set(index, value);
          onChanged();
        } else {
          rowsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
       */
      public Builder setRows(
          int index, com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.set(index, builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
       */
      public Builder addRows(com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.add(value);
          onChanged();
        } else {
          rowsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
       */
      public Builder addRows(
          int index, com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.add(index, value);
          onChanged();
        } else {
          rowsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
       */
      public Builder addRows(
          com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.add(builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
       */
      public Builder addRows(
          int index, com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.add(index, builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
       */
      public Builder addAllRows(
          java.lang.Iterable<? extends com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row> values) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          super.addAll(values, rows_);
          onChanged();
        } else {
          rowsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
       */
      public Builder clearRows() {
        if (rowsBuilder_ == null) {
          rows_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          rowsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
       */
      public Builder removeRows(int index) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.remove(index);
          onChanged();
        } else {
          rowsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
       */
      public com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row.Builder getRowsBuilder(
          int index) {
        return getRowsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
       */
      public com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.RowOrBuilder getRowsOrBuilder(
          int index) {
        if (rowsBuilder_ == null) {
          return rows_.get(index);  } else {
          return rowsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
       */
      public java.util.List<? extends com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.RowOrBuilder> 
           getRowsOrBuilderList() {
        if (rowsBuilder_ != null) {
          return rowsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rows_);
        }
      }
      /**
       * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
       */
      public com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row.Builder addRowsBuilder() {
        return getRowsFieldBuilder().addBuilder(
            com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row.getDefaultInstance());
      }
      /**
       * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
       */
      public com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row.Builder addRowsBuilder(
          int index) {
        return getRowsFieldBuilder().addBuilder(
            index, com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row.getDefaultInstance());
      }
      /**
       * <code>repeated .sysdev.das.DasResultSet.Row rows = 2;</code>
       */
      public java.util.List<com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row.Builder> 
           getRowsBuilderList() {
        return getRowsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row, com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row.Builder, com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.RowOrBuilder> 
          getRowsFieldBuilder() {
        if (rowsBuilder_ == null) {
          rowsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row, com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.Row.Builder, com.ctrip.sysdev.das.domain.DasResultSet.InnerResultSet.RowOrBuilder>(
                  rows_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          rows_ = null;
        }
        return rowsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:sysdev.das.DasResultSet)
    }

    static {
      defaultInstance = new InnerResultSet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:sysdev.das.DasResultSet)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sysdev_das_DasResultSet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sysdev_das_DasResultSet_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sysdev_das_DasResultSet_Row_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sysdev_das_DasResultSet_Row_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023das/ResultSet.proto\022\nsysdev.das\"`\n\014Das" +
      "ResultSet\022\014\n\004last\030\001 \002(\010\022*\n\004rows\030\002 \003(\0132\034." +
      "sysdev.das.DasResultSet.Row\032\026\n\003Row\022\017\n\007co" +
      "lumns\030\001 \003(\014B\035\n\033com.ctrip.sysdev.das.doma" +
      "in"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_sysdev_das_DasResultSet_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_sysdev_das_DasResultSet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sysdev_das_DasResultSet_descriptor,
              new java.lang.String[] { "Last", "Rows", });
          internal_static_sysdev_das_DasResultSet_Row_descriptor =
            internal_static_sysdev_das_DasResultSet_descriptor.getNestedTypes().get(0);
          internal_static_sysdev_das_DasResultSet_Row_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sysdev_das_DasResultSet_Row_descriptor,
              new java.lang.String[] { "Columns", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
